default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: openflights_dev

test:
  <<: *default
  database: openflights_test

production:
  <<: *default
  database: openflights_production
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['DATABASE_HOST'] || 'db' %>

